### ISSUE TITLE
@actions/core package need to be updated

### ISSUE THREAD

**Issue by GerryFerdinandus** [editorconfig-checker/action-editorconfig-checker#11]
Build server give this warning:
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

_Action authors who are using the toolkit should update the @actions/core package to v1.10.0 or greater to get the updated saveState and setOutput functions._

Can you update
https://github.com/editorconfig-checker/action-editorconfig-checker/blob/d4fca16fc71adef10fbe101903b654449fa9570c/package.json#L8

And release a updated version v1

Thanks

**Comment by mstruebing** [comment]
With release 2.0.0 this should be done:

Release: https://github.com/editorconfig-checker/action-editorconfig-checker/releases/tag/v2.0.0
PR: https://github.com/editorconfig-checker/action-editorconfig-checker/pull/19
