### ISSUE TITLE
Need to publish new version with latest commits

### ISSUE THREAD

**Issue by takanuva15** [editorconfig-checker/action-editorconfig-checker#12]
Hi, it looks like new commits were added to fix issues with v1.0.0. My build was not working with this action until I changed my file to pull the latest from main via
```yaml
    - name: Run EditorConfig Linter
      uses: editorconfig-checker/action-editorconfig-checker@main
```

Can you please publish a new version (eg v1.0.1) that contains all the new commits so I can reference that instead of the main branch?

**Comment by mstruebing** [comment]
Sorry it took so long, we have v2 now: https://github.com/editorconfig-checker/action-editorconfig-checker/releases/tag/v2.0.0

Related: https://github.com/editorconfig-checker/action-editorconfig-checker/issues/13
