### ISSUE TITLE
No actual v1 tag

### ISSUE THREAD

**Issue by eugene-babichenko** [editorconfig-checker/action-editorconfig-checker#9]
You need to have a `v1` for your README to work. Only `v1.0.0` is present.

**Comment by mstruebing** [comment]
Thank you, would you mind to create a PR to fix that?

**Comment by eugene-babichenko** [comment]
It requires to push a git tag, I don’t think it can be done in a PR. Or are you suggesting to just fix the documentation?

**Comment by mstruebing** [comment]
I thought fixing the documentation would be the easier way, do you think it's better to fix the tag?

**Comment by eugene-babichenko** [comment]
Well, seems like it is conventional approach. For example, if you look at https://github.com/actions/checkout they have multiple `v2.x.x` tags and `v2` is pointing to the latest of `v2.x.x` tags.

**Comment by mstruebing** [comment]
Thank you, you convinced me. It's done :)
